# * Settings marked with * are advanced settings that won't appear in the Streamlit page and can only be modified manually in config.py
# recommend to set in streamlit page
version: "2.2.3"
## ======================== Basic Settings ======================== ##
display_language: "zh-CN"

# API settings
api:
  key: 'sk-123456'
  base_url: 'http://127.0.0.1:1234'
  model: 'qwen2.5-14b-instruct-1m'

# Language settings
source_language: "auto" # Source language, set to "auto" for auto-detection
detected_language: "" # Store detected language (reset when manually set)
target_language: "简体中文"  # Target language for translation

# Whether to burn subtitles into the video
burn_subtitles: false

## ======================== Advanced Settings ======================== ##
subtitle:
  # *Maximum length of each subtitle line in characters
  max_length: 75
  # *Translated subtitles are slightly larger than source subtitles, affecting the reference length for subtitle splitting
  target_multiplier: 1.2
  # *Number of characters per second for readability
  chars_per_second: 15

# *Summary length, set low to 2k if using local LLM
summary_length: 8000

# *Number of LLM multi-threaded accesses, set to 1 if using local LLM
max_workers: 4
# *Maximum number of words for the first rough cut, below 18 will cut too finely affecting translation, above 22 is too long and will make subsequent subtitle splitting difficult to align
max_split_length: 20

# *Whether to reflect the translation result in the original text
reflect_translate: true

# *Whether to pause after extracting professional terms and before translation, allowing users to manually adjust the terminology table output\log\terminology.json
pause_before_translate: false





## ======================== Additional settings 请勿修改======================== ##
# Whisper model directory
model_dir: './_model_cache'

# Supported upload video formats
allowed_video_formats:
- 'mp4'
- 'mov'
- 'avi'
- 'mkv'
- 'flv'
- 'wmv'
- 'webm'

allowed_audio_formats:
- 'wav'
- 'mp3'
- 'flac'
- 'm4a'

# LLMs that support returning JSON format
llm_support_json:
- 'gpt-4o'
- 'gpt-4o-mini'
- 'gemini-2.0-flash'
- 'deepseek-chat'

# Spacy models
spacy_model_map:
  en: 'en_core_web_md'
  ru: 'ru_core_news_md'
  fr: 'fr_core_news_md'
  ja: 'ja_core_news_md'
  es: 'es_core_news_md'
  de: 'de_core_news_md'
  it: 'it_core_news_md'
  zh: 'zh_core_web_md'

# Languages that use space as separator
language_split_with_space:
- 'en'
- 'es'
- 'fr'
- 'de'
- 'it'
- 'ru'

# Languages that do not use space as separator
language_split_without_space:
- 'zh'
- 'ja'
